
version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Sa_P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  your-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sql-server
    networks:
      - app-network
    #environment:
    #  ASPNETCORE_ENVIRONMENT: "Development"  # Đặt môi trường phát triển

networks:
  app-network:
    driver: bridge
